require('config.globals')
require('config.options')
require('config.neovide')
require('config.lazy')
require('config.autocmds')
require('config.commands')
require('config.keymaps')
require('config.local_settings')
