_G.augroup = vim.api.nvim_create_augroup
_G.autocmd = vim.api.nvim_create_autocmd

---Global nvim api aliases
_G.nvim = {
  clear_autocmds = vim.api.nvim_clear_autocmds,
  del_augroup_by_id = vim.api.nvim_del_augroup_by_id,
  del_augroup_by_name = vim.api.nvim_del_augroup_by_name,
  del_autocmd = vim.api.nvim_del_autocmd,
  exec_autocmds = vim.api.nvim_exec_autocmds,
  get_autocmds = vim.api.nvim_get_autocmds,

  exec2 = vim.api.nvim_exec2,
  paste = vim.api.nvim_paste,
  put = vim.api.nvim_put,
  input = vim.api.nvim_input,
  echo = vim.api.nvim_echo,
  feedkeys = vim.api.nvim_feedkeys,
  replace_termcodes = vim.api.nvim_replace_termcodes,
  eval_statusline = vim.api.nvim_eval_statusline,
  get_current_line = vim.api.nvim_get_current_line,
  set_current_line = vim.api.nvim_set_current_line,
  get_mode = vim.api.nvim_get_mode,
  get_keymap = vim.api.nvim_get_keymap,
  get_runtime_file = vim.api.nvim_get_runtime_file,
  open_term = vim.api.nvim_open_term,

  get_namespaces = vim.api.nvim_get_namespaces,
  buf_clear_namespace = vim.api.nvim_buf_clear_namespace,
  create_namespace = vim.api.nvim_create_namespace,

  get_context = vim.api.nvim_get_context,
  load_context = vim.api.nvim_load_context,

  get_hl = vim.api.nvim_get_hl,
  set_hl = vim.api.nvim_set_hl,
  get_hl_id_by_name = vim.api.nvim_get_hl_id_by_name,
  get_hl_ns = vim.api.nvim_get_hl_ns,

  del_mark = vim.api.nvim_del_mark,
  get_mark = vim.api.nvim_get_mark,
  buf_set_extmark = vim.api.nvim_buf_set_extmark,
  buf_get_extmark_by_id = vim.api.nvim_buf_get_extmark_by_id,
  buf_get_extmarks = vim.api.nvim_buf_get_extmarks,
  buf_del_extmark = vim.api.nvim_buf_del_extmark,
  buf_set_mark = vim.api.nvim_buf_set_mark,

  win_call = vim.api.nvim_win_call,
  win_close = vim.api.nvim_win_close,
  win_del_var = vim.api.nvim_win_del_var,
  win_get_var = vim.api.nvim_win_get_var,
  win_set_var = vim.api.nvim_win_set_var,
  win_get_buf = vim.api.nvim_win_get_buf,
  win_set_buf = vim.api.nvim_win_set_buf,
  win_get_cursor = vim.api.nvim_win_get_cursor,
  win_set_cursor = vim.api.nvim_win_set_cursor,
  win_get_height = vim.api.nvim_win_get_height,
  win_set_height = vim.api.nvim_win_set_height,
  win_get_width = vim.api.nvim_win_get_width,
  win_set_width = vim.api.nvim_win_set_width,
  win_get_number = vim.api.nvim_win_get_number,
  win_get_position = vim.api.nvim_win_get_position,
  win_get_tabpage = vim.api.nvim_win_get_tabpage,
  win_hide = vim.api.nvim_win_hide,
  win_is_valid = vim.api.nvim_win_is_valid,
  win_set_hl_ns = vim.api.nvim_win_is_valid,
  win_text_height = vim.api.nvim_win_text_height,

  list_bufs = vim.api.nvim_list_bufs,
  get_current_buf = vim.api.nvim_get_current_buf,
  set_current_buf = vim.api.nvim_set_current_buf,
  buf_is_loaded = vim.api.nvim_buf_is_loaded,
  buf_is_valid = vim.api.nvim_buf_is_valid,
  buf_set_lines = vim.api.nvim_buf_set_lines,
  buf_get_lines = vim.api.nvim_buf_get_lines,
  buf_delete = vim.api.nvim_buf_delete,
  create_buf = vim.api.nvim_create_buf,

  list_wins = vim.api.list_wins,
  get_current_win = vim.api.nvim_get_current_win,
  set_current_win = vim.api.nvim_set_current_win,

  list_tabs = vim.api.list_tabs,
  get_current_tabpage = vim.api.nvim_get_current_tabpage,
  set_current_tabpage = vim.api.nvim_set_current_tabpage,

  list_chans = vim.api.nvim_list_chans,
  chan_send = vim.api.nvim_chan_send,
  get_chan_info = vim.api.nvim_get_chan_info,

  parse_cmd = vim.api.nvim_parse_cmd,
  buf_create_user_command = vim.api.nvim_buf_create_user_command,
  buf_del_user_command = vim.api.nvim_buf_del_user_command,
  create_user_command = vim.api.nvim_create_user_command,
  del_user_command = vim.api.nvim_del_user_command,
}
